//Plank John


var json = {
	"data1": {
		"fear": ["Fear Level: ", "Psalm 144:1"],
		"apocalypse": ["Apocalypse: ", "Zombie"],
		"firearm": ["Firearm: ", "yes"],
		"ammo": ["Ammo: ", "yes"],
        "melee": ["Melee Weapon: ", "yes"],
		"canned": ["Canned: ", "yes"],
		"water": ["Water: ", "no"],
		"chain":["Chain Mesh Suit: ", "no"],
		"map": ["Topographical: ", "no"],
		"leatherman": ["Leatherman: ", "yes"],
		"rucksack": ["Rucksack: ", "yes"],
		"boots": ["Boots", "yes"],
		"matches": ["Matches: ", "yes"],
		"p38": ["P38: ", "yes"],
		"intestinal": ["Intestinal Fortitude: ", "yes"],
		"item": ["Item: ", "Zombie Spray"],
		"date": ["World Ended: ", "2020-05-24"],
		"email": ["Email: ", "fidleronthegreen@yahoo.com"],
		"comments": ["Comments: ", "Suck it cruel world"],
		"readiness": ["Readiness: ", "11"]
	},
	"data2": {
		"fear": ["Fear Level: ", "Are you kidding me?"],
		"apocalypse": ["Apocalypse: ", "Natural"],
		"firearm": ["Firearm: ", "yes"],
		"ammo": ["Ammo: ", "yes"],
        "melee": ["Melee Weapon: ", "no"],
		"canned": ["Canned: ", "yes"],
		"water": ["Water: ", "no"],
		"chain":["Chain Mesh Suit: ", "no"],
		"map": ["Topographical: ", "yes"],
		"leatherman": ["Leatherman: ", "yes"],
		"rucksack": ["Rucksack: ", "yes"],
		"boots": ["Boots", "yes"],
		"matches": ["Matches: ", "yes"],
		"p38": ["P38: ", "yes"],
		"intestinal": ["Intestinal Fortitude: ", "yes"],
		"item": ["Item: ", "Bible"],
		"date": ["World Ended: ", "2015-05-24"],
		"email": ["Email: ", "momma@yahoo.com"],
		"comments": ["Comments: ", "To live is to die"],
		"readiness": ["Readiness: ", "8"]
	},
	"data3": {
		"fear": ["Fear Level: ", "Opps I crapped my pants"],
		"apocalypse": ["Apocalypse: ", "Atomic"],
		"firearm": ["Firearm: ", "yes"],
		"ammo": ["Ammo: ", "yes"],
        "melee": ["Melee Weapon: ", "yes"],
		"canned": ["Canned: ", "no"],
		"water": ["Water: ", "yes"],
		"chain":["Chain Mesh Suit: ", "no"],
		"map": ["Topographical: ", "yes"],
		"leatherman": ["Leatherman: ", "yes"],
		"rucksack": ["Rucksack: ", "no"],
		"boots": ["Boots", "yes"],
		"matches": ["Matches: ", "no"],
		"p38": ["P38: ", "yes"],
		"intestinal": ["Intestinal Fortitude: ", "yes"],
		"item": ["Item: ", "Sunscreen"],
		"date": ["World Ended: ", "2014-05-23"],
		"email": ["Email: ", "daddy@yahoo.com"],
		"comments": ["Comments: ", "Rather be fishing"],
		"readiness": ["Readiness: ", "4"]		
	}
};